### ISSUE TITLE
Develop preliminary Animation/Keyframe APIs

### ISSUE THREAD

**Issue by boazsender** [Abacus/Abacus#43]

**Comment by mzgoddard** [comment]
First pass of abacus.animation.js merged in commit 274f2805c7

Missing layer.removeFrame and could use a lot more unit tests.

**Comment by mzgoddard** [comment]
Reopened since I didn't "finish" it. (layer.removeFrame)

**Comment by boazsender** [comment]
You could close this one, since you developed a "preliminary api", and make a new one with more specifics about what you have to do.
