### ISSUE TITLE
Abacus.clone cannot clone ArrayBufferViews in Firefox

### ISSUE THREAD

**Issue by mzgoddard** [Abacus/Abacus#50]
``` javascript
Abacus.clone(new Float32Array([1,2]))
```

returns following error in Firefox 7.0.1 on Mac OS 10.6.8 (taken from FireBug)

```
TypeError: value is not a non-null object
(undefined="[object Float32Array]")abacus.js (line 55)
[Break On This Error] })( obj )); 
```

**Comment by rwaldron** [comment]
I'll look into this now

**Comment by rwaldron** [comment]
ArrayBufferViews ( ie. Float32Array objects ) aren't built from Array.prototype

```
> var f = new Float32Array([ 1, 2 ])

> Array.isArray(f);
false

> f.slice
undefined

```

I'll see what I can find about copying ArrayBufferViews

**Comment by mzgoddard** [comment]
Copies can be made by constructing a new typed array with the original as its first argument.

But I am not sure yet how to test whether a given object is an ArrayBufferView in a clean way. Nor how to generalize such construction.

**Comment by rwaldron** [comment]
I'm not opposed to having a check for `instanceof ArrayBufferView` and then creating a copy base on that, but is there anyway to tell which type to make? (ie. Float32, Float64 etc. )
