### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by mzgoddard** [Abacus/Abacus#62]
Looking at the repo, readme file, and a cursory look at the Wiki, I have found no mention of a license for Abacus. Is it MIT, BSD, GPL, Mozilla, Apache, or some esoteric license? Is it even Open Source? Currently this cannot easily be determined by anyone through reading the currently available documentation.

Personally I'm always a MIT and BSD fan, but I am not super knowledgable in the details and nuances of choosing a license for a project.

**Comment by rwaldron** [comment]
I'd say this is MIT Lic. I nominate you to add it.

**Comment by mzgoddard** [comment]
Cool. I would do it in an instant, but who should we assign the copyright to? Me? Boaz? Bocoup? Gradient? Mozilla?

We all have our hands in this ...

Since the push, to my knowledge, originated from Boaz and Bocoup, maybe it should be one of those two?

@boazsender @secretrobotron

**Comment by mzgoddard** [comment]
Push as in push for Abacus to exist.

**Comment by rwaldron** [comment]
Why not "donate" it to Apache?

**Comment by mzgoddard** [comment]
What is involved with "donating" it to Apache? I'm afraid that is outside my realm of knowledge.

**Comment by rwaldron** [comment]
Well, TBH, I have no idea. I know that PhoneGap and Google Wave were donated... That's really the extent I that I know about it.

**Comment by boazsender** [comment]
Why don't we put it in the public domain?: http://creativecommons.org/publicdomain/zero/1.0

**Comment by mzgoddard** [comment]
I looked into CC0 a bit further and found this:
http://wiki.creativecommons.org/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F

I was wondering about the implications with working Abacus under CC0 with other licenses. This answered it nicely.

More link following:
http://www.gnu.org/licenses/license-list.html#CC0

CC0 is GPL Compatible.
