### ISSUE TITLE
JSHint complains at usage of "delete" as a property name of an object

### ISSUE THREAD

**Issue by boazsender** [Abacus/Abacus#65]
This prevents me from creating a delete property. Should I just call it destroy, or can we let `Abacus.store.delete( id )` exist, for example?

**Comment by rwaldron** [comment]
destroy is fine

**Comment by boazsender** [comment]
Delete would be more inline with the REST semantics I think we should encourage.

Is `{ delete: function(){ ... }}` bad practice?

**Comment by rwaldron** [comment]
'delete' is a reserved word in JavaScript. Older browsers incorrectly apply Identifier semantics to IdentifierName (ie property names). I don't care if we use delete, it just means that Abacus won't work in Safari (FF, Chrome and Opera get it right). So, if Safari isnt nec. then go ahead

**Comment by boazsender** [comment]
Good call. I'll keep it as destroy. Closing this issue.
